---
- name: Test omit as default
  hosts: localhost
  gather_facts: false
  vars:
    users:
      - firstname: Test
  tasks:
    - name: Testing
      ansible.builtin.debug:
        msg: "{{ firstname | default(omit, true) | lower }}"
